// src/lib/components/HomePanel.svelte
<script lang="ts">
  import AccountCard from '$lib/components/AccountCard.svelte';
  import LogPanel from '$lib/components/LogPanel.svelte';
  import QuotaSummaryCard from '$lib/components/QuotaSummaryCard.svelte';
  import type { AppSnapshotDto } from '$lib/types/app';

  type Props = {
    snapshot: AppSnapshotDto;
    busy?: boolean;
    onSelectAccount: (accountId: string) => void;
    onLogin: () => void;
  };

  let { snapshot, busy = false, onSelectAccount, onLogin }: Props = $props();

  const selectedAccount = () => snapshot.accounts.find((account) => account.id === snapshot.selectedAccountId) ?? null;
  const loginTimeText = () => formatDate(snapshot.loginState.lastLoginTime);

  function formatDate(value: string | null) {
    if (!value) return '-';
    const date = new Date(value);
    if (Number.isNaN(date.getTime())) return value;
    return date.toLocaleString('zh-CN', { hour12: false });
  }
</script>

<div class="page-grid home fade-in">
  <div class="stack">
    <section class="card">
      <div class="card-header">
        <div>
          <h2 class="card-title">主页</h2>
          <div class="card-subtitle">选择账号后执行校园网 HTTP 认证</div>
        </div>
        <span class="pill" class:warn={snapshot.loginState.running}>{snapshot.loginState.resultText}</span>
      </div>
      <div class="card-body stack">
        <div class="grid-2">
          <div class="metric">
            <span class="metric-label">当前内网 IPv4</span>
            <span class="metric-value mono">{snapshot.network.ip}</span>
          </div>
          <div class="metric">
            <span class="metric-label">最近一次登录时间</span>
            <span class="metric-value mono">{loginTimeText()}</span>
          </div>
        </div>

        <div class="form-field">
          <label class="field-label" for="account-select">登录账号</label>
          <select
            class="select"
            id="account-select"
            disabled={busy || snapshot.loginState.running || snapshot.accounts.length === 0}
            value={snapshot.selectedAccountId}
            onchange={(event) => onSelectAccount(event.currentTarget.value)}
          >
            {#if snapshot.accounts.length === 0}
              <option value="">请先在状态页添加账号</option>
            {:else}
              {#each snapshot.accounts as account}
                <option value={account.id}>{account.remarkName || account.username}（{account.username}）</option>
              {/each}
            {/if}
          </select>
        </div>

        <div class="row">
          <button
            class="action-button"
            type="button"
            disabled={busy || snapshot.loginState.running || snapshot.accounts.length === 0}
            onclick={onLogin}
          >
            {snapshot.loginState.running ? '登录中...' : snapshot.accounts.length === 0 ? '请先添加账号' : '开始登录'}
          </button>
          <span class="inline-note">{snapshot.loginState.message}</span>
        </div>
      </div>
    </section>

    {#if selectedAccount()}
      <AccountCard account={selectedAccount()!} selected compact actionEnabled={!busy} />
    {/if}

    <QuotaSummaryCard title="账号配额" quota={snapshot.poolQuota} loading={snapshot.refreshState.running} />
  </div>

  <LogPanel logs={snapshot.logs} />
</div>

// src/lib/features/home/HomePanel.tsx
import { LogIn } from 'lucide-react';
import { Button } from '$lib/components/ui/button';
import { Card } from '$lib/components/ui/card';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '$lib/components/ui/select';
import type { AppSnapshotDto } from '$lib/types/app';
import { formatDateTime } from '$lib/features/shared/format';
import { ProgressBar } from '$lib/features/shared/progress';
import { LogPanel } from '$lib/features/logs/LogPanel';

type Props = {
  snapshot: AppSnapshotDto;
  busy: boolean;
  onSelectAccount: (accountId: string) => void;
  onLogin: () => void;
};

export function HomePanel({ snapshot, busy, onSelectAccount, onLogin }: Props) {
  const activeAccount = snapshot.accounts.find((account) => account.id === snapshot.selectedAccountId) ?? null;

  return (
    <section className="panel-in grid min-h-0 flex-1 grid-rows-[auto_auto_1fr] gap-4">
      <Card className="grid gap-4 p-5">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h2 className="text-xl font-semibold">MUC-student</h2>
            <div className="mt-2 grid gap-1 text-sm text-muted-foreground">
              <span>内网 IPv4：{snapshot.network.ip || 'unknown'}</span>
              <span>最近登录：{formatDateTime(snapshot.loginState.lastLoginTime)}</span>
            </div>
          </div>
          <Button disabled={busy || snapshot.loginState.running || snapshot.accounts.length === 0} onClick={onLogin} className="min-w-32">
            <LogIn />
            {snapshot.loginState.running ? '登录中' : snapshot.accounts.length === 0 ? '无账号' : '登录'}
          </Button>
        </div>

        <Select value={snapshot.selectedAccountId || undefined} onValueChange={onSelectAccount} disabled={busy || snapshot.loginState.running || snapshot.accounts.length === 0}>
          <SelectTrigger className="max-w-xl">
            <SelectValue placeholder="请先添加账号" />
          </SelectTrigger>
          <SelectContent>
            {snapshot.accounts.map((account) => (
              <SelectItem key={account.id} value={account.id}>
                {account.remarkName || account.username}（{account.username}）
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </Card>

      {activeAccount && (
        <Card className="grid gap-3 p-5">
          <div className="flex items-center justify-between gap-4">
            <div>
              <h3 className="text-base font-semibold">账号配额</h3>
              <p className="text-sm text-muted-foreground">{activeAccount.remarkName || activeAccount.username}</p>
            </div>
            <span className="font-mono text-sm text-muted-foreground">{activeAccount.snapshot?.progressPercent?.toFixed(1) ?? '--'}%</span>
          </div>
          <ProgressBar value={activeAccount.snapshot?.progressPercent} loading={snapshot.refreshState.running} />
          <div className="grid gap-1 text-sm text-muted-foreground sm:grid-cols-3">
            <span>在线设备：{(activeAccount.snapshot?.onlineDeviceCountText || '').trim() || '-'}</span>
            <span>已用流量：{activeAccount.snapshot?.usedTrafficText || '-'}</span>
            <span>
              总流量：{activeAccount.snapshot?.productBalanceText || '-'}
              {activeAccount.snapshot?.includedPackageText ? <b className="ml-1 font-medium text-emerald-500">[{activeAccount.snapshot.includedPackageText.trim()}]</b> : null}
            </span>
          </div>
        </Card>
      )}

      <LogPanel logs={snapshot.logs} />
    </section>
  );
}
