// src/lib/components/AccountCard.svelte
<script lang="ts">
  import type { AccountDto } from '$lib/types/app';

  type Props = {
    account: AccountDto;
    selected?: boolean;
    actionEnabled?: boolean;
    compact?: boolean;
    onEdit?: (accountId: string) => void;
    onDelete?: (accountId: string) => void;
    onLogout?: (accountId: string) => void;
  };

  let {
    account,
    selected = false,
    actionEnabled = true,
    compact = false,
    onEdit,
    onDelete,
    onLogout
  }: Props = $props();

  const displayPercent = (value: number | null | undefined) =>
    typeof value === 'number' ? Math.max(0, Math.min(100, value)) : null;

  const ringLabel = (value: number | null | undefined) => {
    const percent = displayPercent(value);
    return percent === null ? '--' : `${percent.toFixed(1)}%`;
  };

  const ringStyle = (value: number | null | undefined) => {
    const percent = displayPercent(value) ?? 0;
    return `--ring-percent: ${percent}%`;
  };

  const isExhausted = (value: number | null | undefined) => typeof value === 'number' && value >= 100;
</script>

<article class:selected class="list-item account-card" class:compact>
  <div class="ring" class:small={compact} style={ringStyle(account.snapshot?.progressPercent)}>
    {ringLabel(account.snapshot?.progressPercent)}
  </div>

  <div class="stack tight">
    <div class="split">
      <div>
        <div class="row">
          <strong>{account.remarkName || account.username}</strong>
          {#if account.isCurrentOnline}
            <span class="pill success">本机在线</span>
          {/if}
          {#if selected}
            <span class="pill">登录目标</span>
          {/if}
          {#if isExhausted(account.snapshot?.progressPercent)}
            <span class="pill danger">已用尽</span>
          {/if}
        </div>
        <div class="inline-note mono">账号：{account.username}</div>
      </div>
      {#if !compact}
        <div class="row">
          <button class="action-button secondary" type="button" onclick={() => onEdit?.(account.id)}>编辑</button>
          <button class="action-button ghost" type="button" onclick={() => onDelete?.(account.id)}>删除</button>
          {#if account.canLogoutLocalDevice}
            <button class="action-button warn" disabled={!actionEnabled} type="button" onclick={() => onLogout?.(account.id)}>
              下线本机
            </button>
          {/if}
        </div>
      {/if}
    </div>

    <div class="grid-3">
      <div class="metric">
        <span class="metric-label">在线设备</span>
        <span class="metric-value">{account.snapshot?.onlineDeviceCountText || '-'}</span>
      </div>
      <div class="metric">
        <span class="metric-label">已用流量</span>
        <span class="metric-value">{account.snapshot?.usedTrafficText || '-'}</span>
      </div>
      <div class="metric">
        <span class="metric-label">账户总流量</span>
        <span class="metric-value">{account.snapshot?.productBalanceText || '-'}</span>
      </div>
    </div>

    {#if account.snapshot?.includedPackageText || account.snapshot?.detailText}
      <div class="inline-note">
        {#if account.snapshot?.includedPackageText}<span class="pill success">{account.snapshot.includedPackageText}</span>{/if}
        {#if account.snapshot?.detailText}<span>{account.snapshot.detailText}</span>{/if}
      </div>
    {/if}
  </div>
</article>

// src/lib/features/status/AccountCard.tsx
import { Edit3, LogOut, Trash2 } from 'lucide-react';
import { Badge } from '$lib/components/ui/badge';
import { Button } from '$lib/components/ui/button';
import { Card } from '$lib/components/ui/card';
import type { AccountDto } from '$lib/types/app';
import { cn } from '$lib/utils';
import { formatDateTime } from '$lib/features/shared/format';
import { TrafficRing } from '$lib/features/shared/progress';

type Props = {
  account: AccountDto;
  selected?: boolean;
  actionEnabled?: boolean;
  onEdit: (accountId: string) => void;
  onDelete: (accountId: string) => void;
  onLogout: (accountId: string) => void;
};

export function AccountCard({ account, selected = false, actionEnabled = true, onEdit, onDelete, onLogout }: Props) {
  return (
    <Card className={cn('grid grid-cols-[84px_1fr_auto] gap-4 p-4', selected && 'border-primary shadow-[0_0_0_1px_hsl(var(--primary))]')}>
      <TrafficRing value={account.snapshot?.progressPercent} />
      <div className="min-w-0 space-y-2">
        <div className="flex flex-wrap items-center gap-2">
          <h3 className="truncate text-base font-semibold">{account.remarkName || account.username}</h3>
          {account.isCurrentOnline && <Badge className="bg-primary/15 text-primary hover:bg-primary/15">本机在线</Badge>}
        </div>
        <div className="grid gap-x-5 gap-y-1 text-sm text-muted-foreground sm:grid-cols-2">
          <span>账号：{account.username}</span>
          <span>在线设备：{(account.snapshot?.onlineDeviceCountText || '').trim() || '-'}</span>
          <span>已用流量：{account.snapshot?.usedTrafficText || '-'}</span>
          <span>
            总流量：{account.snapshot?.productBalanceText || '-'}
            {account.snapshot?.includedPackageText ? <b className="ml-1 font-medium text-emerald-500">[{account.snapshot.includedPackageText.trim()}]</b> : null}
          </span>
          <span className="sm:col-span-2">更新时间：{formatDateTime(account.snapshot?.queriedAt)}</span>
        </div>
      </div>
      <div className="flex items-start gap-2">
        {account.canLogoutLocalDevice && (
          <Button size="icon" disabled={!actionEnabled} onClick={() => onLogout(account.id)} aria-label="下线本机">
            <LogOut />
          </Button>
        )}
        <Button size="icon" variant="secondary" disabled={!actionEnabled} onClick={() => onEdit(account.id)} aria-label="编辑账号">
          <Edit3 />
        </Button>
        <Button size="icon" variant="ghost" disabled={!actionEnabled} onClick={() => onDelete(account.id)} aria-label="删除账号">
          <Trash2 />
        </Button>
      </div>
    </Card>
  );
}
