// src/lib/components/SettingsPanel.svelte
<script lang="ts">
  import type { AppSnapshotDto, PreferenceDto } from '$lib/types/app';

  type Props = {
    snapshot: AppSnapshotDto;
    busy?: boolean;
    onUpdatePreferences: (preferences: PreferenceDto) => void;
  };

  let { snapshot, busy = false, onUpdatePreferences }: Props = $props();

  const setPreference = (patch: Partial<PreferenceDto>) => {
    onUpdatePreferences({ ...snapshot.preferences, ...patch });
  };
</script>

<div class="page-grid settings fade-in">
  <section class="card">
    <div class="card-header">
      <div>
        <h2 class="card-title">设置</h2>
        <div class="card-subtitle">只保留功能等价需要的三个偏好项</div>
      </div>
    </div>
    <div class="card-body stack">
      <label class="list-item split">
        <div>
          <strong>关闭窗口时最小化到托盘</strong>
          <div class="inline-note">开启后，关闭主窗口只隐藏到系统托盘。</div>
        </div>
        <input
          style="width: auto"
          type="checkbox"
          disabled={busy}
          checked={snapshot.preferences.minimizeToTrayOnClose}
          onchange={(event) => setPreference({ minimizeToTrayOnClose: event.currentTarget.checked })}
        />
      </label>

      <label class="list-item split">
        <div>
          <strong>开机自动启动</strong>
          <div class="inline-note">登录 Windows 时自动启动程序。</div>
        </div>
        <input
          style="width: auto"
          type="checkbox"
          disabled={busy}
          checked={snapshot.preferences.launchOnStartup}
          onchange={(event) => setPreference({ launchOnStartup: event.currentTarget.checked })}
        />
      </label>

      <label class="list-item split">
        <div>
          <strong>流量用完后自动切换账号</strong>
          <div class="inline-note">按最近使用优先且未用尽流量的现有规则切换。</div>
        </div>
        <input
          style="width: auto"
          type="checkbox"
          disabled={busy}
          checked={snapshot.preferences.autoSwitchAccountOnTrafficExhausted}
          onchange={(event) => setPreference({ autoSwitchAccountOnTrafficExhausted: event.currentTarget.checked })}
        />
      </label>
    </div>
  </section>

  <section class="card">
    <div class="card-header">
      <div>
        <h2 class="card-title">接口地址</h2>
        <div class="card-subtitle">认证网关和自助面板严格分开</div>
      </div>
    </div>
    <div class="card-body grid-2">
      <div class="metric">
        <span class="metric-label">认证 URL</span>
        <span class="metric-value mono">http://rz.muc.edu.cn/srun_portal_pc.php?ac_id=1&amp;</span>
      </div>
      <div class="metric">
        <span class="metric-label">流量查询 URL</span>
        <span class="metric-value mono">http://192.168.2.231:8800/home</span>
      </div>
    </div>
  </section>
</div>

// src/lib/features/settings/SettingsPanel.tsx
import { Card } from '$lib/components/ui/card';
import { Input } from '$lib/components/ui/input';
import { Switch } from '$lib/components/ui/switch';
import type { AppSnapshotDto, PreferenceDto } from '$lib/types/app';

type Props = {
  snapshot: AppSnapshotDto;
  busy: boolean;
  onUpdatePreferences: (preferences: PreferenceDto) => void;
};

export function SettingsPanel({ snapshot, busy, onUpdatePreferences }: Props) {
  const setPreference = (patch: Partial<PreferenceDto>) => {
    onUpdatePreferences({ ...snapshot.preferences, ...patch });
  };

  return (
    <section className="panel-in flex min-h-0 flex-1 flex-col gap-4">
      <h2 className="text-xl font-semibold">设置</h2>
      <Card className="divide-y divide-border p-5">
        <PreferenceRow
          title="关闭窗口时最小化到托盘"
          checked={snapshot.preferences.minimizeToTrayOnClose}
          disabled={busy}
          onCheckedChange={(checked) => setPreference({ minimizeToTrayOnClose: checked })}
        />
        <PreferenceRow
          title="开机自动启动"
          checked={snapshot.preferences.launchOnStartup}
          disabled={busy}
          onCheckedChange={(checked) => setPreference({ launchOnStartup: checked })}
        />
        <PreferenceRow
          title="流量用完后自动切换账号"
          checked={snapshot.preferences.autoSwitchAccountOnTrafficExhausted}
          disabled={busy}
          onCheckedChange={(checked) => setPreference({ autoSwitchAccountOnTrafficExhausted: checked })}
        />
      </Card>

      <Card className="grid gap-4 p-5">
        <h3 className="text-base font-semibold">接口地址</h3>
        <div className="grid gap-3">
          <Input readOnly value="http://rz.muc.edu.cn/srun_portal_pc.php?ac_id=1&" className="font-mono text-xs" />
          <Input readOnly value="http://192.168.2.231:8800/home" className="font-mono text-xs" />
        </div>
      </Card>
    </section>
  );
}

type PreferenceRowProps = {
  title: string;
  checked: boolean;
  disabled: boolean;
  onCheckedChange: (checked: boolean) => void;
};

function PreferenceRow({ title, checked, disabled, onCheckedChange }: PreferenceRowProps) {
  return (
    <label className="flex cursor-pointer items-center justify-between gap-4 py-4 first:pt-0 last:pb-0">
      <span className="text-sm font-medium">{title}</span>
      <Switch checked={checked} disabled={disabled} onCheckedChange={onCheckedChange} />
    </label>
  );
}
