// src/lib/components/AccountDialog.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { AccountDto, AccountInput, AccountUpdateInput } from '$lib/types/app';

  type SubmitDetail = AccountInput | AccountUpdateInput;
  type Props = {
    mode: 'create' | 'edit';
    account?: AccountDto | null;
    busy?: boolean;
  };

  let { mode, account = null, busy = false }: Props = $props();
  const dispatch = createEventDispatcher<{ close: void; submit: SubmitDetail }>();

  let remarkName = $state('');
  let username = $state('');
  let password = $state('');
  let localError = $state('');

  $effect(() => {
    remarkName = account?.remarkName ?? '';
    username = account?.username ?? '';
    password = '';
  });

  function submit() {
    localError = '';
    const remark = remarkName.trim();
    const user = username.trim();
    if (!remark || !user) {
      localError = '请填写备注名和账号';
      return;
    }
    if (mode === 'create' && !password) {
      localError = '请填写密码';
      return;
    }
    if (mode === 'edit' && account) {
      dispatch('submit', {
        accountId: account.id,
        remarkName: remark,
        username: user,
        password: password ? password : null
      });
      return;
    }
    dispatch('submit', { remarkName: remark, username: user, password });
  }
</script>

<div class="overlay" role="presentation" onclick={(event) => event.target === event.currentTarget && dispatch('close')}>
  <div class="dialog" role="dialog" aria-modal="true" aria-labelledby="account-dialog-title">
    <div class="dialog-header">
      <div>
        <h2 class="card-title" id="account-dialog-title">{mode === 'create' ? '添加账号' : '编辑账号'}</h2>
      </div>
      <button class="action-button ghost" type="button" onclick={() => dispatch('close')}>关闭</button>
    </div>
    <div class="dialog-body">
      <form class="stack" onsubmit={(event) => { event.preventDefault(); submit(); }}>
        <div class="form-grid">
          <label class="form-field">
            <span class="field-label">备注名</span>
            <input class="input" bind:value={remarkName} autocomplete="off" />
          </label>
          <label class="form-field">
            <span class="field-label">账号</span>
            <input class="input" bind:value={username} autocomplete="username" />
          </label>
          <label class="form-field full">
            <span class="field-label">密码</span>
            <input
              class="input"
              bind:value={password}
              type="password"
              autocomplete={mode === 'create' ? 'new-password' : 'current-password'}
              placeholder={mode === 'edit' ? '不填则保留原密码' : ''}
            />
          </label>
        </div>
        {#if localError}
          <div class="error-banner"><strong>{localError}</strong></div>
        {/if}
        <div class="dialog-actions">
          <button class="action-button secondary" type="button" onclick={() => dispatch('close')}>取消</button>
          <button class="action-button" disabled={busy} type="submit">保存</button>
        </div>
      </form>
    </div>
  </div>
</div>

// src/lib/features/accounts/AccountDialog.tsx
import { useEffect, useState } from 'react';
import { Alert, AlertDescription } from '$lib/components/ui/alert';
import { Button } from '$lib/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '$lib/components/ui/dialog';
import { Input } from '$lib/components/ui/input';
import { Label } from '$lib/components/ui/label';
import type { AccountDto, AccountInput, AccountUpdateInput } from '$lib/types/app';

type Props = {
  open: boolean;
  mode: 'create' | 'edit';
  account?: AccountDto | null;
  busy: boolean;
  onClose: () => void;
  onSubmit: (input: AccountInput | AccountUpdateInput) => void;
};

export function AccountDialog({ open, mode, account = null, busy, onClose, onSubmit }: Props) {
  const [remarkName, setRemarkName] = useState('');
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [localError, setLocalError] = useState('');

  useEffect(() => {
    setRemarkName(account?.remarkName ?? '');
    setUsername(account?.username ?? '');
    setPassword('');
    setLocalError('');
  }, [account, open]);

  const submit = (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    setLocalError('');
    const remark = remarkName.trim();
    const user = username.trim();
    if (!remark || !user) {
      setLocalError('请填写备注名和账号');
      return;
    }
    if (mode === 'create' && !password) {
      setLocalError('请填写密码');
      return;
    }
    if (mode === 'edit' && account) {
      onSubmit({ accountId: account.id, remarkName: remark, username: user, password: password ? password : null });
      return;
    }
    onSubmit({ remarkName: remark, username: user, password });
  };

  return (
    <Dialog open={open} onOpenChange={(value) => !value && onClose()}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{mode === 'create' ? '添加账号' : '编辑账号'}</DialogTitle>
          <DialogDescription>{mode === 'create' ? '将新的校园网账号添加到号池。' : '修改已有账号。'}</DialogDescription>
        </DialogHeader>
        <form className="grid gap-4" onSubmit={submit}>
          <div className="grid gap-2">
            <Label htmlFor="remarkName">备注名</Label>
            <Input id="remarkName" value={remarkName} onChange={(event) => setRemarkName(event.target.value)} autoComplete="off" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="username">账号</Label>
            <Input id="username" value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="password">密码</Label>
            <Input id="password" type="password" value={password} onChange={(event) => setPassword(event.target.value)} autoComplete={mode === 'create' ? 'new-password' : 'current-password'} placeholder={mode === 'edit' ? '不填则保留原密码' : ''} />
          </div>
          {localError && (
            <Alert variant="destructive">
              <AlertDescription>{localError}</AlertDescription>
            </Alert>
          )}
          <DialogFooter>
            <Button type="button" variant="ghost" onClick={onClose}>
              取消
            </Button>
            <Button type="submit" disabled={busy}>
              保存
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}
