// src/lib/features/status/StatusPanel.tsx
import { Button, Card, Select, Text } from '@fluentui/react-components';
import { AddRegular, ArrowClockwiseRegular, ChevronRightRegular } from '@fluentui/react-icons';
import { useMemo, useState } from 'react';
import type { AccountDto, AppSnapshotDto, UiState } from '$lib/types/app';
import { iconSize, useShellStyles } from '$lib/features/shared/layout';
import { AccountCard } from './AccountCard';
import { QuotaSummaryCard } from './QuotaSummaryCard';

type Props = {
  snapshot: AppSnapshotDto;
  sortMode: UiState['sortMode'];
  busy: boolean;
  onSortMode: (mode: UiState['sortMode']) => void;
  onAdd: () => void;
  onEdit: (accountId: string) => void;
  onDelete: (accountId: string) => void;
  onLogout: (accountId: string) => void;
  onRefresh: () => void;
};

function remainingSortKey(account: AccountDto) {
  const percent = account.snapshot?.progressPercent;
  if (typeof percent !== 'number') return -1;
  return 100 - percent;
}

export function StatusPanel({ snapshot, sortMode, busy, onSortMode, onAdd, onEdit, onDelete, onLogout, onRefresh }: Props) {
  const styles = useShellStyles();
  const [collapsed, setCollapsed] = useState(true);
  const sortedAccounts = useMemo(() => {
    const accounts = [...snapshot.accounts];
    if (sortMode === 'remainingDesc') accounts.sort((a, b) => remainingSortKey(b) - remainingSortKey(a));
    if (sortMode === 'nameAsc') accounts.sort((a, b) => `${a.remarkName}${a.username}`.localeCompare(`${b.remarkName}${b.username}`, 'zh-CN'));
    return accounts;
  }, [snapshot.accounts, sortMode]);

  const activeAccounts = sortedAccounts.filter((account) => account.isCurrentOnline || (account.snapshot?.progressPercent ?? -1) < 100);
  const exhaustedAccounts = sortedAccounts.filter((account) => !account.isCurrentOnline && (account.snapshot?.progressPercent ?? -1) >= 100);
  const actionEnabled = !busy && !snapshot.refreshState.running && !snapshot.loginState.running;

  return (
    <section className={styles.stack} style={{ flex: 1 }}>
      <div className={styles.toolbar}>
        <Text className={styles.muted} style={{ marginRight: 'auto' }}>
          已添加 {snapshot.accounts.length} 个账号
        </Text>
        <Select value={sortMode} onChange={(event) => onSortMode(event.target.value as UiState['sortMode'])}>
          <option value="default">默认排序</option>
          <option value="remainingDesc">剩余量高到低</option>
          <option value="nameAsc">姓名 A-Z</option>
        </Select>
        <Button appearance="subtle" icon={<ArrowClockwiseRegular style={iconSize} />} disabled={busy || snapshot.refreshState.running} onClick={onRefresh}>
          刷新
        </Button>
        <Button appearance="primary" icon={<AddRegular style={iconSize} />} disabled={busy} onClick={onAdd}>
          添加账号
        </Button>
      </div>

      <QuotaSummaryCard quota={snapshot.poolQuota} loading={snapshot.refreshState.running} />

      <div className={styles.scrollArea}>
        {snapshot.accounts.length === 0 ? (
          <Card appearance="filled" className={styles.compactCard} style={{ textAlign: 'center' }}>
            <Text className={styles.muted}>还没有账号。</Text>
          </Card>
        ) : (
          <div className={styles.stack}>
            {activeAccounts.map((account) => (
              <AccountCard
                key={account.id}
                account={account}
                selected={account.id === snapshot.selectedAccountId}
                actionEnabled={actionEnabled}
                onEdit={onEdit}
                onDelete={onDelete}
                onLogout={onLogout}
              />
            ))}

            {exhaustedAccounts.length > 0 && (
              <div className={styles.stack}>
                <Button
                  appearance="subtle"
                  icon={<ChevronRightRegular style={{ ...iconSize, transform: collapsed ? 'rotate(0deg)' : 'rotate(90deg)' }} />}
                  onClick={() => setCollapsed((value) => !value)}
                >
                  已用尽账号（{exhaustedAccounts.length}）
                </Button>
                {!collapsed &&
                  exhaustedAccounts.map((account) => (
                    <AccountCard
                      key={account.id}
                      account={account}
                      selected={account.id === snapshot.selectedAccountId}
                      actionEnabled={actionEnabled}
                      onEdit={onEdit}
                      onDelete={onDelete}
                      onLogout={onLogout}
                    />
                  ))}
              </div>
            )}
          </div>
        )}
      </div>
    </section>
  );
}

// src/lib/components/StatusPanel.svelte
<script lang="ts">
  import AccountCard from '$lib/components/AccountCard.svelte';
  import QuotaSummaryCard from '$lib/components/QuotaSummaryCard.svelte';
  import type { AccountDto, AppSnapshotDto, UiState } from '$lib/types/app';

  type Props = {
    snapshot: AppSnapshotDto;
    sortMode: UiState['sortMode'];
    busy?: boolean;
    onSortMode: (mode: UiState['sortMode']) => void;
    onAdd: () => void;
    onEdit: (accountId: string) => void;
    onDelete: (accountId: string) => void;
    onLogout: (accountId: string) => void;
    onRefresh: () => void;
  };

  let {
    snapshot,
    sortMode,
    busy = false,
    onSortMode,
    onAdd,
    onEdit,
    onDelete,
    onLogout,
    onRefresh
  }: Props = $props();

  const sortedAccounts = () => {
    const accounts = [...snapshot.accounts];
    if (sortMode === 'remainingDesc') {
      accounts.sort((a, b) => remainingSortKey(b) - remainingSortKey(a));
    }
    if (sortMode === 'nameAsc') {
      accounts.sort((a, b) => `${a.remarkName}${a.username}`.localeCompare(`${b.remarkName}${b.username}`, 'zh-CN'));
    }
    return orderByCurrentOnline(accounts);
  };

  function orderByCurrentOnline(accounts: AccountDto[]) {
    const current = accounts.filter((account) => account.isCurrentOnline);
    const exhausted = accounts.filter((account) => !account.isCurrentOnline && (account.snapshot?.progressPercent ?? -1) >= 100);
    const active = accounts.filter((account) => !account.isCurrentOnline && (account.snapshot?.progressPercent ?? -1) < 100);
    return [...current, ...exhausted, ...active];
  }

  function remainingSortKey(account: AccountDto) {
    const percent = account.snapshot?.progressPercent;
    if (typeof percent !== 'number') return -1;
    return 100 - percent;
  }
</script>

<div class="page-grid status fade-in">
  <QuotaSummaryCard title="号池总配额" quota={snapshot.poolQuota} loading={snapshot.refreshState.running} />

  <section class="card">
    <div class="card-header">
      <div>
        <h2 class="card-title">状态</h2>
        <div class="card-subtitle">账号快照、在线设备、本机下线入口</div>
      </div>
      <div class="row">
        <select class="select" style="width: 180px" value={sortMode} onchange={(event) => onSortMode(event.currentTarget.value as UiState['sortMode'])}>
          <option value="default">默认排序</option>
          <option value="remainingDesc">剩余量从高到低</option>
          <option value="nameAsc">姓名 A-Z</option>
        </select>
        <button class="action-button secondary" disabled={busy || snapshot.refreshState.running} type="button" onclick={onRefresh}>
          {snapshot.refreshState.running ? '刷新中...' : '刷新状态'}
        </button>
        <button class="action-button" type="button" onclick={onAdd}>添加账号</button>
      </div>
    </div>

    <div class="card-body">
      {#if snapshot.accounts.length === 0}
        <div class="inline-note">还没有账号，先点右上角添加账号。</div>
      {:else}
        <div class="list">
          {#each sortedAccounts() as account (account.id)}
            <AccountCard
              {account}
              selected={account.id === snapshot.selectedAccountId}
              actionEnabled={!busy && !snapshot.refreshState.running && !snapshot.loginState.running}
              onEdit={onEdit}
              onDelete={onDelete}
              onLogout={onLogout}
            />
          {/each}
        </div>
      {/if}
    </div>
  </section>
</div>
